/**
 * The one list of example questions this product offers anywhere.
 *
 * Every entry names the MCP tool that answers it, and that pairing is the
 * point: the tools are the complete, fixed set of things this system can do
 * (`backend/internal/mcptools`), so an example tied to one of them is
 * provably answerable. Nothing here is aspirational copy.
 *
 * Deliberately NOT generated by asking the model to describe its own
 * capabilities. A model listing what it can do is a fresh hallucination
 * surface — it would happily offer "compare your food costs to industry
 * benchmarks" — and suggesting a question the product cannot answer is the
 * same class of lie as inventing a number. This list changes only when a
 * tool is added.
 */
export interface ExampleQuestion {
  text: string
  /** The MCP tool that answers it — the grounding, not decoration. */
  tool:
    | 'get_daily_summary'
    | 'get_margin_delta'
    | 'list_discrepancies'
    | 'get_promotion_roi'
    | 'list_negative_roi_promotions'
    | 'compare_platform_economics'
    | 'get_period_totals'
    | 'get_expense_pattern_by_day_of_month'
  /** Short label for grouping in the "what can I ask" surface. */
  topic: string
}

export const EXAMPLE_QUESTIONS: ExampleQuestion[] = [
  {
    text: 'How did we do on 2026-08-07?',
    tool: 'get_daily_summary',
    topic: 'One day',
  },
  {
    text: 'Which days had discrepancies between 2026-08-01 and 2026-08-14?',
    tool: 'list_discrepancies',
    topic: 'Problems caught',
  },
  {
    text: 'Compare total margin for 2026-08-01 to 2026-08-07 against 2026-08-08 to 2026-08-14',
    tool: 'get_margin_delta',
    topic: 'Week over week',
  },
  {
    text: 'Which promotions lost money between 2026-08-01 and 2026-08-14?',
    tool: 'list_negative_roi_promotions',
    topic: 'Promotions',
  },
  {
    text: 'Show me the ROI for every iFood campaign between 2026-08-01 and 2026-08-14',
    tool: 'get_promotion_roi',
    topic: 'Campaign ROI',
  },
  {
    text: 'Which platform costs me more in commission — iFood or Just Eat Takeaway — between 2026-08-01 and 2026-08-14?',
    tool: 'compare_platform_economics',
    topic: 'Platform comparison',
  },
  {
    text: 'What was our best day between 2026-08-01 and 2026-08-14, and what was the total margin for the period?',
    tool: 'get_period_totals',
    topic: 'Period totals',
  },
  {
    text: 'Which day of the month costs the most, on average, between 2026-08-01 and 2026-08-14?',
    tool: 'get_expense_pattern_by_day_of_month',
    topic: 'Recurring costs',
  },
]

/**
 * What the product answers, in one sentence, for the header of a
 * "here's what I can do" surface. Written by hand from the tool set rather
 * than asked of the model, for the same reason the list above is — but the
 * date range is a real parameter, not baked into this string. It used to be
 * hardcoded to "2026-08-01 through 2026-08-14" (the original 14-day
 * dataset's opening window), which silently went stale the moment the
 * dataset grew to a multi-year synthetic history behind it — the sentence
 * kept claiming a period that was no longer the only one this data covers.
 * Callers get the real, current range from `useDataCoverage` (lib/) and pass
 * it in here, so this claim can never drift from what the backend actually
 * answers against.
 */
export function buildCapabilitySummary(coveragePeriod: string): string {
  return `I answer questions about one restaurant’s reconciled daily margin, its period totals and best/worst days, its discrepancies, its promotion ROI, and how its delivery platforms compare on commission and promo cost — for ${coveragePeriod}, the only period this data covers.`
}
