/**
 * Pure logic behind the guided question composer: the 8 real, answerable
 * categories (one per typed MCP tool in contracts/mcp-tools.md), the
 * structured parameters each one actually takes, and the deterministic
 * template that turns a filled-in set of parameters into the exact
 * natural-language question string that gets submitted through the normal
 * `/api/ask` flow (ChatPanel's existing `submitQuestion` — see
 * QuestionComposer.tsx).
 *
 * This is the guided composer's equivalent of exampleQuestions.ts: a
 * hand-written mapping from the fixed tool set to plain language, never
 * generated by asking the model to describe its own capabilities (same
 * reasoning as that file's own doc comment — a model listing what it can do
 * is a fresh hallucination surface). The difference is that file offers one
 * fixed example string per tool; this one builds a NEW, well-formed
 * question from an owner's own choices, but can still never reach past the
 * 8 tools below, so it can never compose a question the system will refuse
 * for asking about a capability that doesn't exist.
 *
 * Kept framework-free (no React) so the composition logic is trivial to
 * unit-test on its own, independent of the step UI in QuestionComposer.tsx.
 */

/** A plain "YYYY-MM-DD" calendar date, matching every date field on the wire. */
export type IsoDate = string

export interface DateRange {
  start: IsoDate
  end: IsoDate
}

/**
 * The one and only place the guided composer names its 8 categories. Order
 * here is the order Step 1 renders them in.
 *
 * `tool` is the real MCP tool name each category maps to — kept for tests
 * and for anyone reading this file, but never rendered in the UI (the whole
 * point of a plain-language category is that "get_expense_pattern_by_day_of_month"
 * never appears on screen).
 */
export interface GuidedCategory {
  id: GuidedCategoryId
  tool: string
  /** Sentence-case, verb-first button label. No terminal punctuation. */
  label: string
  /** One-line helper sentence shown under the label. */
  description: string
}

export type GuidedCategoryId =
  | 'daily_summary'
  | 'margin_delta'
  | 'discrepancies'
  | 'promotion_roi'
  | 'negative_roi_promotions'
  | 'platform_economics'
  | 'period_totals'
  | 'expense_pattern_by_day'

export const GUIDED_CATEGORIES: GuidedCategory[] = [
  {
    id: 'daily_summary',
    tool: 'get_daily_summary',
    label: 'Check a single day',
    description: 'Margin, sales, and costs for one date.',
  },
  {
    id: 'margin_delta',
    tool: 'get_margin_delta',
    label: 'Compare two periods',
    description: 'See how margin changed between two date ranges.',
  },
  {
    id: 'discrepancies',
    tool: 'list_discrepancies',
    label: 'Check for discrepancies',
    description: 'Duplicate orders, refunds, and other flagged issues.',
  },
  {
    id: 'promotion_roi',
    tool: 'get_promotion_roi',
    label: "Check a promotion's return",
    description: "How one campaign, or a platform's campaigns, performed.",
  },
  {
    id: 'negative_roi_promotions',
    tool: 'list_negative_roi_promotions',
    label: 'Find money-losing promotions',
    description: 'Campaigns that cost more than they brought in.',
  },
  {
    id: 'platform_economics',
    tool: 'compare_platform_economics',
    label: 'Compare delivery platforms',
    description: 'Commission and promo cost, side by side.',
  },
  {
    id: 'period_totals',
    tool: 'get_period_totals',
    label: 'Get period totals',
    description: 'Total margin, plus your best and worst day.',
  },
  {
    id: 'expense_pattern_by_day',
    tool: 'get_expense_pattern_by_day_of_month',
    label: 'Find your priciest day of the month',
    description: 'Which day of the month tends to cost the most, on average.',
  },
]

/**
 * The fixed, known set of delivery platforms `compare_platform_economics`
 * and `get_promotion_roi` recognize — mirrors the backend's own
 * `knownComparatorPlatforms` (internal/mcptools/platform_comparison_tools.go).
 * Deliberately hardcoded rather than fetched: it is a fixed list on the Go
 * side too (FR-003 requires showing a platform with zero orders, which rules
 * out discovering the list by scanning which platforms happen to appear in
 * a given period), so a real API round-trip would add latency for a value
 * that changes only when a Go file changes.
 */
export const KNOWN_PLATFORMS: { value: string; label: string }[] = [
  { value: 'ifood', label: 'iFood' },
  { value: 'just_eat_takeaway', label: 'Just Eat Takeaway' },
]

/** One real campaign the owner can pick, sourced live from `GET /api/promotions`. */
export interface GuidedCampaign {
  campaignId: string
  platform: string
}

export type GuidedParams =
  | { category: 'daily_summary'; date: IsoDate }
  | { category: 'margin_delta'; periodA: DateRange; periodB: DateRange }
  | { category: 'discrepancies'; scope: 'single_date'; date: IsoDate }
  | { category: 'discrepancies'; scope: 'period'; period: DateRange }
  | { category: 'promotion_roi'; mode: 'campaign'; campaignId: string }
  | {
      category: 'promotion_roi'
      mode: 'platform_period'
      platform: string
      period: DateRange
    }
  | { category: 'negative_roi_promotions'; period: DateRange }
  | { category: 'platform_economics'; period: DateRange }
  | { category: 'period_totals'; period: DateRange }
  | { category: 'expense_pattern_by_day'; period: DateRange }

/** True when both dates are present and `start` is on or before `end`. */
export function isChronologicalRange(range: Partial<DateRange>): range is DateRange {
  if (!range.start || !range.end) return false
  return range.start <= range.end
}

function platformLabel(value: string): string {
  return KNOWN_PLATFORMS.find((p) => p.value === value)?.label ?? value
}

/**
 * Turns a filled-in, valid set of guided params into the exact
 * self-contained natural-language question string that gets submitted.
 * Every date is stated explicitly (never "last week" or "this month") for
 * the same reason `comparePeriod.ts`'s `buildCompareToLastPeriodQuestion`
 * always has: the ambiguity gate resolves an explicit, fully-dated range far
 * more reliably than a relative phrase. Phrasing mirrors the app's own
 * existing example questions (exampleQuestions.ts) and backend-generated
 * follow-ups (suggestions.go) wherever an equivalent already exists, so a
 * guided question reads exactly like a question this product would suggest
 * on its own.
 */
export function composeGuidedQuestion(params: GuidedParams): string {
  switch (params.category) {
    case 'daily_summary':
      return `How did we do on ${params.date}?`

    case 'margin_delta':
      return `Compare total margin for ${params.periodA.start} to ${params.periodA.end} against ${params.periodB.start} to ${params.periodB.end}`

    case 'discrepancies':
      return params.scope === 'single_date'
        ? `Were there any discrepancies on ${params.date}?`
        : `Which days had discrepancies between ${params.period.start} and ${params.period.end}?`

    case 'promotion_roi':
      return params.mode === 'campaign'
        ? `What was the ROI for campaign ${params.campaignId}?`
        : `Show me the ROI for every ${platformLabel(params.platform)} campaign between ${params.period.start} and ${params.period.end}`

    case 'negative_roi_promotions':
      return `Which promotions lost money between ${params.period.start} and ${params.period.end}?`

    case 'platform_economics':
      return `Which platform costs me more in commission — ${KNOWN_PLATFORMS[0].label} or ${KNOWN_PLATFORMS[1].label} — between ${params.period.start} and ${params.period.end}?`

    case 'period_totals':
      return `What was our best day between ${params.period.start} and ${params.period.end}, and what was the total margin for the period?`

    case 'expense_pattern_by_day':
      return `Which day of the month costs the most, on average, between ${params.period.start} and ${params.period.end}?`
  }
}

/**
 * The step-2 form's working state: every field any category could possibly
 * need, all optional, since only some apply to the category currently
 * selected. `scope`/`mode` are the sub-choices `discrepancies` and
 * `promotion_roi` each need (a date vs. a period; a campaign vs. a
 * platform+period) before the rest of their fields make sense.
 */
export interface GuidedDraft {
  date?: string
  period?: Partial<DateRange>
  periodA?: Partial<DateRange>
  periodB?: Partial<DateRange>
  scope?: 'single_date' | 'period'
  mode?: 'campaign' | 'platform_period'
  platform?: string
  campaignId?: string
}

/**
 * Converts the free-form step-2 draft into a strict, composable
 * `GuidedParams` — or `null` while it's still incomplete. This is the single
 * source of truth for "is this category's form filled in well enough to
 * move on", so the Continue button's disabled state and the question
 * actually composed can never disagree with each other.
 */
export function toGuidedParams(
  category: GuidedCategoryId,
  draft: GuidedDraft,
): GuidedParams | null {
  switch (category) {
    case 'daily_summary':
      return draft.date ? { category, date: draft.date } : null

    case 'margin_delta':
      return isChronologicalRange(draft.periodA ?? {}) && isChronologicalRange(draft.periodB ?? {})
        ? { category, periodA: draft.periodA as DateRange, periodB: draft.periodB as DateRange }
        : null

    case 'discrepancies':
      if (draft.scope === 'period') {
        return isChronologicalRange(draft.period ?? {})
          ? { category, scope: 'period', period: draft.period as DateRange }
          : null
      }
      return draft.date ? { category, scope: 'single_date', date: draft.date } : null

    case 'promotion_roi':
      if (draft.mode === 'platform_period') {
        return draft.platform && isChronologicalRange(draft.period ?? {})
          ? {
              category,
              mode: 'platform_period',
              platform: draft.platform,
              period: draft.period as DateRange,
            }
          : null
      }
      return draft.campaignId
        ? { category, mode: 'campaign', campaignId: draft.campaignId }
        : null

    case 'negative_roi_promotions':
    case 'platform_economics':
    case 'period_totals':
    case 'expense_pattern_by_day':
      return isChronologicalRange(draft.period ?? {})
        ? { category, period: draft.period as DateRange }
        : null
  }
}
