/**
 * Pure logic behind the guided question composer: the structured parameters
 * each capability actually takes, and the deterministic template that turns a
 * filled-in set of parameters into the exact natural-language question string
 * that gets submitted through the normal `/api/ask` flow (ChatPanel's existing
 * `submitQuestion` — see QuestionComposer.tsx).
 *
 * WHAT the composer can offer is no longer decided here. That list lives in
 * `@/capabilities` — the one authoritative catalog this app's Help page and
 * composer both read, kept honest by a contract test against the real Go tool
 * registry and advisor kinds. This module owns only HOW each capability is
 * parameterised and phrased, which is code, not a list.
 *
 * Nothing here is generated by asking the model to describe its own
 * capabilities (same reasoning as exampleQuestions.ts's own doc comment — a
 * model listing what it can do is a fresh hallucination surface). Every
 * question this module can build is one of the catalog's computed
 * capabilities, so it can never compose a question the system will refuse for
 * naming a capability that doesn't exist.
 *
 * Kept framework-free (no React) so the composition logic is trivial to
 * unit-test on its own, independent of the step UI in QuestionComposer.tsx.
 */

import {
  COMPUTED_CAPABILITIES,
  findAdvisoryCapability,
  type AdvisoryCapability,
  type BusinessInsightKind,
  type ComputedCapability,
  type ComputedCapabilityId,
} from '@/capabilities'

/** A plain "YYYY-MM-DD" calendar date, matching every date field on the wire. */
export type IsoDate = string

export interface DateRange {
  start: IsoDate
  end: IsoDate
}

/**
 * The composer's Step 1 categories — now DERIVED from `@/capabilities`'
 * computed capabilities rather than restated here. This used to be a second
 * hand-maintained list; deriving it means a tool the catalog knows about can
 * never be missing from the composer, and the catalog's own contract test
 * means the catalog can never be missing a tool the Go server registers.
 *
 * The names are kept (`GuidedCategory`, `GUIDED_CATEGORIES`, `GuidedCategoryId`)
 * because the Help page and this module's tests already read them, and because
 * "category" is the right word for what Step 1 renders.
 */
export type GuidedCategory = ComputedCapability
export type GuidedCategoryId = ComputedCapabilityId

export const GUIDED_CATEGORIES: GuidedCategory[] = COMPUTED_CAPABILITIES

/**
 * The fixed, known set of delivery platforms `compare_platform_economics`
 * and `get_promotion_roi` recognize — mirrors the backend's own
 * `knownComparatorPlatforms` (internal/mcptools/platform_comparison_tools.go).
 * Deliberately hardcoded rather than fetched: it is a fixed list on the Go
 * side too (FR-003 requires showing a platform with zero orders, which rules
 * out discovering the list by scanning which platforms happen to appear in
 * a given period), so a real API round-trip would add latency for a value
 * that changes only when a Go file changes.
 */
export const KNOWN_PLATFORMS: { value: string; label: string }[] = [
  { value: 'ifood', label: 'iFood' },
  { value: 'just_eat_takeaway', label: 'Just Eat Takeaway' },
]

/** One real campaign the owner can pick, sourced live from `GET /api/promotions`. */
export interface GuidedCampaign {
  campaignId: string
  platform: string
}

export type GuidedParams =
  | { category: 'daily_summary'; date: IsoDate }
  | { category: 'margin_delta'; periodA: DateRange; periodB: DateRange }
  | { category: 'discrepancies'; scope: 'single_date'; date: IsoDate }
  | { category: 'discrepancies'; scope: 'period'; period: DateRange }
  | { category: 'promotion_roi'; mode: 'campaign'; campaignId: string }
  | {
      category: 'promotion_roi'
      mode: 'platform_period'
      platform: string
      period: DateRange
    }
  | { category: 'negative_roi_promotions'; period: DateRange }
  | { category: 'platform_economics'; period: DateRange }
  | { category: 'period_totals'; period: DateRange }
  | { category: 'expense_pattern_by_day'; period: DateRange }

/** True when both dates are present and `start` is on or before `end`. */
export function isChronologicalRange(range: Partial<DateRange>): range is DateRange {
  if (!range.start || !range.end) return false
  return range.start <= range.end
}

/**
 * The real, known data window every date picker is bounded to
 * (`useDataCoverage`, threaded through as `QuestionComposerProps.minDate` /
 * `maxDate`). `null`/`undefined` means "no known bound on this side" — the
 * composer itself has no opinion on what counts as too early or too late;
 * that judgment belongs entirely to the live coverage data.
 */
export interface DateBounds {
  minDate?: string | null
  maxDate?: string | null
}

/**
 * True when `value` falls within `bounds`, treating a missing bound as no
 * restriction on that side. Plain ISO-8601 string comparison is sufficient
 * and exact here — the same trick `isChronologicalRange` already relies on —
 * because every date on the wire is a fixed-width "YYYY-MM-DD".
 */
export function isDateWithinBounds(value: IsoDate, bounds?: DateBounds): boolean {
  if (!value) return false
  if (bounds?.minDate && value < bounds.minDate) return false
  if (bounds?.maxDate && value > bounds.maxDate) return false
  return true
}

const MONTH_ABBREVIATIONS = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
]

/**
 * "2026-08-14" -> "Aug 14, 2026". Formatted by hand, deliberately never
 * routed through `Date`/`toLocaleDateString`: those interpret an ISO date as
 * UTC midnight and then render it in the browser's local zone, which can
 * silently shift the displayed day by one for anyone west of UTC — exactly
 * the kind of subtly-wrong date this composer exists to prevent, so it must
 * not appear in the composer's own error copy.
 */
export function formatDisplayDate(iso: IsoDate): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso)
  if (!match) return iso
  const [, year, month, day] = match
  const label = MONTH_ABBREVIATIONS[Number(month) - 1]
  if (!label) return iso
  return `${label} ${Number(day)}, ${year}`
}

/**
 * The inline copy for a date outside `bounds` — `null` while `value` is
 * empty (nothing to flag yet; `required` already covers "not filled in") or
 * already in range. Named after what's wrong and states the fix in the same
 * breath (ux-writing's what→how, dropping "why" since "outside our data"
 * is self-evident from the stated range) — never a bare "Invalid date".
 */
export function dateRangeErrorMessage(value: IsoDate, bounds?: DateBounds): string | null {
  if (!value || isDateWithinBounds(value, bounds)) return null
  const { minDate, maxDate } = bounds ?? {}
  if (minDate && maxDate) {
    return `Choose a date between ${formatDisplayDate(minDate)} and ${formatDisplayDate(maxDate)}.`
  }
  if (maxDate) return `Choose a date on or before ${formatDisplayDate(maxDate)}.`
  if (minDate) return `Choose a date on or after ${formatDisplayDate(minDate)}.`
  return null
}

/** `isChronologicalRange`, extended to also require both ends fall within `bounds`. */
function isValidRange(range: Partial<DateRange>, bounds?: DateBounds): range is DateRange {
  return (
    isChronologicalRange(range) &&
    isDateWithinBounds(range.start, bounds) &&
    isDateWithinBounds(range.end, bounds)
  )
}

function platformLabel(value: string): string {
  return KNOWN_PLATFORMS.find((p) => p.value === value)?.label ?? value
}

/**
 * Turns a filled-in, valid set of guided params into the exact
 * self-contained natural-language question string that gets submitted.
 * Every date is stated explicitly (never "last week" or "this month") for
 * the same reason `comparePeriod.ts`'s `buildCompareToLastPeriodQuestion`
 * always has: the ambiguity gate resolves an explicit, fully-dated range far
 * more reliably than a relative phrase. Phrasing mirrors the app's own
 * existing example questions (exampleQuestions.ts) and backend-generated
 * follow-ups (suggestions.go) wherever an equivalent already exists, so a
 * guided question reads exactly like a question this product would suggest
 * on its own.
 */
export function composeGuidedQuestion(params: GuidedParams): string {
  switch (params.category) {
    case 'daily_summary':
      return `How did we do on ${params.date}?`

    case 'margin_delta':
      return `Compare total margin for ${params.periodA.start} to ${params.periodA.end} against ${params.periodB.start} to ${params.periodB.end}`

    case 'discrepancies':
      return params.scope === 'single_date'
        ? `Were there any discrepancies on ${params.date}?`
        : `Which days had discrepancies between ${params.period.start} and ${params.period.end}?`

    case 'promotion_roi':
      return params.mode === 'campaign'
        ? `What was the ROI for campaign ${params.campaignId}?`
        : `Show me the ROI for every ${platformLabel(params.platform)} campaign between ${params.period.start} and ${params.period.end}`

    case 'negative_roi_promotions':
      return `Which promotions lost money between ${params.period.start} and ${params.period.end}?`

    case 'platform_economics':
      return `Which platform costs me more in commission — ${KNOWN_PLATFORMS[0].label} or ${KNOWN_PLATFORMS[1].label} — between ${params.period.start} and ${params.period.end}?`

    case 'period_totals':
      return `What was our best day between ${params.period.start} and ${params.period.end}, and what was the total margin for the period?`

    case 'expense_pattern_by_day':
      return `Which day of the month costs the most, on average, between ${params.period.start} and ${params.period.end}?`
  }
}

/**
 * The step-2 form's working state: every field any category could possibly
 * need, all optional, since only some apply to the category currently
 * selected. `scope`/`mode` are the sub-choices `discrepancies` and
 * `promotion_roi` each need (a date vs. a period; a campaign vs. a
 * platform+period) before the rest of their fields make sense.
 */
export interface GuidedDraft {
  date?: string
  period?: Partial<DateRange>
  periodA?: Partial<DateRange>
  periodB?: Partial<DateRange>
  scope?: 'single_date' | 'period'
  mode?: 'campaign' | 'platform_period'
  platform?: string
  campaignId?: string
}

/**
 * Converts the free-form step-2 draft into a strict, composable
 * `GuidedParams` — or `null` while it's still incomplete OR while any date it
 * carries falls outside `bounds` (the real, live data window). This is the
 * single source of truth for "is this category's form filled in well enough
 * to move on", so the Continue button's disabled state, the question
 * actually composed, and an out-of-range date genuinely blocking
 * progression can never disagree with each other — a date the backend
 * cannot answer for must never make it past this function, category by
 * category, exactly like an incomplete or backwards one already can't.
 */
export function toGuidedParams(
  category: GuidedCategoryId,
  draft: GuidedDraft,
  bounds?: DateBounds,
): GuidedParams | null {
  switch (category) {
    case 'daily_summary':
      return draft.date && isDateWithinBounds(draft.date, bounds)
        ? { category, date: draft.date }
        : null

    case 'margin_delta':
      return isValidRange(draft.periodA ?? {}, bounds) && isValidRange(draft.periodB ?? {}, bounds)
        ? { category, periodA: draft.periodA as DateRange, periodB: draft.periodB as DateRange }
        : null

    case 'discrepancies':
      if (draft.scope === 'period') {
        return isValidRange(draft.period ?? {}, bounds)
          ? { category, scope: 'period', period: draft.period as DateRange }
          : null
      }
      return draft.date && isDateWithinBounds(draft.date, bounds)
        ? { category, scope: 'single_date', date: draft.date }
        : null

    case 'promotion_roi':
      if (draft.mode === 'platform_period') {
        return draft.platform && isValidRange(draft.period ?? {}, bounds)
          ? {
              category,
              mode: 'platform_period',
              platform: draft.platform,
              period: draft.period as DateRange,
            }
          : null
      }
      // A campaign id names a real, already-known campaign (fetched live —
      // see fetchKnownCampaigns) rather than a picked date, so `bounds`
      // simply doesn't apply to this branch.
      return draft.campaignId
        ? { category, mode: 'campaign', campaignId: draft.campaignId }
        : null

    case 'negative_roi_promotions':
    case 'platform_economics':
    case 'period_totals':
    case 'expense_pattern_by_day':
      return isValidRange(draft.period ?? {}, bounds)
        ? { category, period: draft.period as DateRange }
        : null
  }
}

// ---------------------------------------------------------------------------
// The advisory path
// ---------------------------------------------------------------------------

/**
 * A request for business ADVICE, as the composer emits it. Deliberately not a
 * bare question string like the computed path's output — advice is a
 * different action with a different destination, and collapsing it into "just
 * another question" is exactly the shape that would hide that.
 *
 * `question` is the grounding question: one of the 8 computed capabilities'
 * own questions, composed by the exact same `composeGuidedQuestion` and
 * therefore guaranteed answerable on identical terms. That two-stage shape is
 * forced by the backend, not chosen for convenience —
 * `httpapi.HandleBusinessInsight` refuses any advice request whose posted
 * `tool_calls` don't re-derive to the claimed kind (spec SC-005), and
 * `BusinessInsightChip` may only fetch advice on an explicit tap (spec
 * FR-014). So there is no "POST the kind and get advice" path to model: the
 * pattern must be computed first, and the owner must then choose to pay for
 * an interpretation of it.
 */
export interface GuidedAdviceRequest {
  insightKind: BusinessInsightKind
  question: string
}

/**
 * How many date ranges an advisory topic's grounding question needs. Only a
 * margin decline is defined relative to another period; every other insight
 * pattern is detected within a single one.
 */
export function advisoryPeriodCount(capability: AdvisoryCapability): 1 | 2 {
  return capability.groundedBy === 'margin_delta' ? 2 : 1
}

/**
 * Normalises the advisory form's draft into the exact draft its grounding
 * category expects. `list_discrepancies` is the only grounding category with a
 * sub-choice, and for advice the answer is never "one day": a discrepancy
 * PATTERN worth advising on is a recurrence, which only a period can show.
 */
function advisoryGroundingDraft(
  capability: AdvisoryCapability,
  draft: GuidedDraft,
): GuidedDraft {
  if (capability.groundedBy === 'discrepancies') {
    return { ...draft, scope: 'period' }
  }
  return draft
}

/**
 * Turns a filled-in advisory form into a `GuidedAdviceRequest`, or `null`
 * while it's incomplete or carries a date outside `bounds` — the same gate,
 * for the same reason, as `toGuidedParams`, and literally the same code path:
 * the grounding question is composed through `toGuidedParams` +
 * `composeGuidedQuestion`, so the advisory path cannot compose a question the
 * computed path wouldn't have.
 */
export function composeAdviceRequest(
  insightKind: BusinessInsightKind,
  draft: GuidedDraft,
  bounds?: DateBounds,
): GuidedAdviceRequest | null {
  const capability = findAdvisoryCapability(insightKind)
  if (!capability) return null
  const params = toGuidedParams(
    capability.groundedBy,
    advisoryGroundingDraft(capability, draft),
    bounds,
  )
  if (!params) return null
  return { insightKind, question: composeGuidedQuestion(params) }
}
