// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answer_cache.sql

package storage

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAnswerCacheHits = `-- name: CountAnswerCacheHits :one
SELECT COUNT(*)::bigint AS total FROM answer_cache_hit
`

func (q *Queries) CountAnswerCacheHits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAnswerCacheHits)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createAnswerCacheHit = `-- name: CreateAnswerCacheHit :one
INSERT INTO answer_cache_hit (
    normalized_question,
    question_text,
    estimated_cost_avoided_usd
) VALUES ($1, $2, $3)
RETURNING id, normalized_question, question_text, estimated_cost_avoided_usd, served_at
`

type CreateAnswerCacheHitParams struct {
	NormalizedQuestion      string         `json:"normalized_question"`
	QuestionText            string         `json:"question_text"`
	EstimatedCostAvoidedUsd pgtype.Numeric `json:"estimated_cost_avoided_usd"`
}

// One row per answer served from cache — a non-interaction, recorded in its
// own ledger rather than as a fabricated question_interaction.
func (q *Queries) CreateAnswerCacheHit(ctx context.Context, arg CreateAnswerCacheHitParams) (AnswerCacheHit, error) {
	row := q.db.QueryRow(ctx, createAnswerCacheHit, arg.NormalizedQuestion, arg.QuestionText, arg.EstimatedCostAvoidedUsd)
	var i AnswerCacheHit
	err := row.Scan(
		&i.ID,
		&i.NormalizedQuestion,
		&i.QuestionText,
		&i.EstimatedCostAvoidedUsd,
		&i.ServedAt,
	)
	return i, err
}

const deleteAllAnswerCacheEntries = `-- name: DeleteAllAnswerCacheEntries :exec
DELETE FROM answer_cache
`

// Invalidation. Called at the START of every ingestion run: new source data
// can change any cached answer, and there is no cheap way to know which, so
// the whole cache is dropped. Correctness after new data beats cache
// retention, always.
func (q *Queries) DeleteAllAnswerCacheEntries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllAnswerCacheEntries)
	return err
}

const getAnswerCacheEntry = `-- name: GetAnswerCacheEntry :one
SELECT normalized_question, original_question, response, origin_cost_usd, created_at FROM answer_cache
WHERE normalized_question = $1
`

// Exact lookup on the normalized question key. Writer/reader:
// internal/answercache only.
func (q *Queries) GetAnswerCacheEntry(ctx context.Context, normalizedQuestion string) (AnswerCache, error) {
	row := q.db.QueryRow(ctx, getAnswerCacheEntry, normalizedQuestion)
	var i AnswerCache
	err := row.Scan(
		&i.NormalizedQuestion,
		&i.OriginalQuestion,
		&i.Response,
		&i.OriginCostUsd,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentDistinctCachedQuestions = `-- name: ListRecentDistinctCachedQuestions :many
SELECT normalized_question, original_question FROM answer_cache
ORDER BY created_at DESC
LIMIT $1
`

type ListRecentDistinctCachedQuestionsRow struct {
	NormalizedQuestion string `json:"normalized_question"`
	OriginalQuestion   string `json:"original_question"`
}

// The bounded candidate set specs/004-semantic-cache's paraphrase classifier
// checks a new question against: the most-recently-cached questions first
// (LIMIT applies the plan's cap — 20 at the call site — before the
// classification prompt is built, per plan.md's "Candidate-set cap" section).
// Already distinct by construction: normalized_question is answer_cache's
// primary key, so this can never return two rows for the same question.
func (q *Queries) ListRecentDistinctCachedQuestions(ctx context.Context, limit int32) ([]ListRecentDistinctCachedQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listRecentDistinctCachedQuestions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentDistinctCachedQuestionsRow
	for rows.Next() {
		var i ListRecentDistinctCachedQuestionsRow
		if err := rows.Scan(&i.NormalizedQuestion, &i.OriginalQuestion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAnswerCacheCostAvoided = `-- name: SumAnswerCacheCostAvoided :one
SELECT COALESCE(SUM(estimated_cost_avoided_usd), 0)::numeric AS total FROM answer_cache_hit
`

// Total model spend the cache has avoided so far.
func (q *Queries) SumAnswerCacheCostAvoided(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumAnswerCacheCostAvoided)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const upsertAnswerCacheEntry = `-- name: UpsertAnswerCacheEntry :one
INSERT INTO answer_cache (
    normalized_question,
    original_question,
    response,
    origin_cost_usd
) VALUES ($1, $2, $3, $4)
ON CONFLICT (normalized_question) DO UPDATE SET
    original_question = EXCLUDED.original_question,
    response          = EXCLUDED.response,
    origin_cost_usd   = EXCLUDED.origin_cost_usd,
    created_at        = now()
RETURNING normalized_question, original_question, response, origin_cost_usd, created_at
`

type UpsertAnswerCacheEntryParams struct {
	NormalizedQuestion string          `json:"normalized_question"`
	OriginalQuestion   string          `json:"original_question"`
	Response           json.RawMessage `json:"response"`
	OriginCostUsd      pgtype.Numeric  `json:"origin_cost_usd"`
}

// Re-answering the same normalized question overwrites the entry rather than
// keeping the older one: the newer response was computed against whatever
// data is current, so it is the one worth serving next time.
func (q *Queries) UpsertAnswerCacheEntry(ctx context.Context, arg UpsertAnswerCacheEntryParams) (AnswerCache, error) {
	row := q.db.QueryRow(ctx, upsertAnswerCacheEntry,
		arg.NormalizedQuestion,
		arg.OriginalQuestion,
		arg.Response,
		arg.OriginCostUsd,
	)
	var i AnswerCache
	err := row.Scan(
		&i.NormalizedQuestion,
		&i.OriginalQuestion,
		&i.Response,
		&i.OriginCostUsd,
		&i.CreatedAt,
	)
	return i, err
}
