// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business_insight_interaction.sql

package storage

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBusinessInsightInteractions = `-- name: CountBusinessInsightInteractions :one
SELECT COUNT(*)::bigint AS total FROM business_insight_interaction
`

func (q *Queries) CountBusinessInsightInteractions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBusinessInsightInteractions)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBusinessInsightInteraction = `-- name: CreateBusinessInsightInteraction :one
INSERT INTO business_insight_interaction (
    kind,
    grounding_tool_calls,
    advice_text,
    model_used,
    input_tokens,
    output_tokens,
    estimated_cost_usd,
    latency_ms
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, kind, grounding_tool_calls, advice_text, model_used, input_tokens, output_tokens, estimated_cost_usd, latency_ms, created_at
`

type CreateBusinessInsightInteractionParams struct {
	Kind               string          `json:"kind"`
	GroundingToolCalls json.RawMessage `json:"grounding_tool_calls"`
	AdviceText         string          `json:"advice_text"`
	ModelUsed          string          `json:"model_used"`
	InputTokens        int32           `json:"input_tokens"`
	OutputTokens       int32           `json:"output_tokens"`
	EstimatedCostUsd   pgtype.Numeric  `json:"estimated_cost_usd"`
	LatencyMs          int32           `json:"latency_ms"`
}

// One row per on-demand business-insight advice call
// (specs/009-business-insight-advisor) — the owner tapped a
// deterministically-derived teaser and a real Claude Sonnet 5 call ran.
// Writer: internal/httpapi's business-insight handler only, alongside
// internal/advisor's model call (Constitution Principle VI).
func (q *Queries) CreateBusinessInsightInteraction(ctx context.Context, arg CreateBusinessInsightInteractionParams) (BusinessInsightInteraction, error) {
	row := q.db.QueryRow(ctx, createBusinessInsightInteraction,
		arg.Kind,
		arg.GroundingToolCalls,
		arg.AdviceText,
		arg.ModelUsed,
		arg.InputTokens,
		arg.OutputTokens,
		arg.EstimatedCostUsd,
		arg.LatencyMs,
	)
	var i BusinessInsightInteraction
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.GroundingToolCalls,
		&i.AdviceText,
		&i.ModelUsed,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCostUsd,
		&i.LatencyMs,
		&i.CreatedAt,
	)
	return i, err
}

const sumBusinessInsightCost = `-- name: SumBusinessInsightCost :one
SELECT COALESCE(SUM(estimated_cost_usd), 0)::numeric AS total FROM business_insight_interaction
`

// The real total this product's advice skill has spent so far — its own
// ledger's sum, never mixed into question_interaction's running total.
func (q *Queries) SumBusinessInsightCost(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumBusinessInsightCost)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}
