// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_error_report.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordClientErrorReport = `-- name: RecordClientErrorReport :one
INSERT INTO client_error_report (message, component, stack, url, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, message, component, stack, url, user_agent, occurred_at
`

type RecordClientErrorReportParams struct {
	Message   string      `json:"message"`
	Component pgtype.Text `json:"component"`
	Stack     pgtype.Text `json:"stack"`
	Url       pgtype.Text `json:"url"`
	UserAgent pgtype.Text `json:"user_agent"`
}

// Backs POST /api/client-errors (frontend/src/components/ErrorBoundary.tsx).
// A pure insert of what the browser reported about itself — no
// interpretation, no join against any other table. See
// migrations/000006_client_error_report.up.sql for why this is its own
// table rather than folded into an existing one.
func (q *Queries) RecordClientErrorReport(ctx context.Context, arg RecordClientErrorReportParams) (ClientErrorReport, error) {
	row := q.db.QueryRow(ctx, recordClientErrorReport,
		arg.Message,
		arg.Component,
		arg.Stack,
		arg.Url,
		arg.UserAgent,
	)
	var i ClientErrorReport
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.Component,
		&i.Stack,
		&i.Url,
		&i.UserAgent,
		&i.OccurredAt,
	)
	return i, err
}
