// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_reconciliation.sql

package storage

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyReconciliationByDate = `-- name: GetDailyReconciliationByDate :one
SELECT date, gross_sales_by_source, commissions, refunds, input_costs, margin, discrepancy_flags, source_row_refs, created_at, updated_at FROM daily_reconciliation
WHERE date = $1
`

// Backs the get_daily_summary MCP tool contract.
func (q *Queries) GetDailyReconciliationByDate(ctx context.Context, date pgtype.Date) (DailyReconciliation, error) {
	row := q.db.QueryRow(ctx, getDailyReconciliationByDate, date)
	var i DailyReconciliation
	err := row.Scan(
		&i.Date,
		&i.GrossSalesBySource,
		&i.Commissions,
		&i.Refunds,
		&i.InputCosts,
		&i.Margin,
		&i.DiscrepancyFlags,
		&i.SourceRowRefs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDailyReconciliationsInPeriod = `-- name: ListDailyReconciliationsInPeriod :many
SELECT date, gross_sales_by_source, commissions, refunds, input_costs, margin, discrepancy_flags, source_row_refs, created_at, updated_at FROM daily_reconciliation
WHERE date >= $1 AND date <= $2
ORDER BY date
`

type ListDailyReconciliationsInPeriodParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

// Backs get_margin_delta / list_discrepancies, which operate over a range.
func (q *Queries) ListDailyReconciliationsInPeriod(ctx context.Context, arg ListDailyReconciliationsInPeriodParams) ([]DailyReconciliation, error) {
	rows, err := q.db.Query(ctx, listDailyReconciliationsInPeriod, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyReconciliation
	for rows.Next() {
		var i DailyReconciliation
		if err := rows.Scan(
			&i.Date,
			&i.GrossSalesBySource,
			&i.Commissions,
			&i.Refunds,
			&i.InputCosts,
			&i.Margin,
			&i.DiscrepancyFlags,
			&i.SourceRowRefs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyReconciliation = `-- name: UpsertDailyReconciliation :one
INSERT INTO daily_reconciliation (
    date,
    gross_sales_by_source,
    commissions,
    refunds,
    input_costs,
    margin,
    discrepancy_flags,
    source_row_refs
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (date) DO UPDATE SET
    gross_sales_by_source = EXCLUDED.gross_sales_by_source,
    commissions           = EXCLUDED.commissions,
    refunds               = EXCLUDED.refunds,
    input_costs           = EXCLUDED.input_costs,
    margin                = EXCLUDED.margin,
    discrepancy_flags     = EXCLUDED.discrepancy_flags,
    source_row_refs       = EXCLUDED.source_row_refs,
    updated_at            = now()
RETURNING date, gross_sales_by_source, commissions, refunds, input_costs, margin, discrepancy_flags, source_row_refs, created_at, updated_at
`

type UpsertDailyReconciliationParams struct {
	Date               pgtype.Date     `json:"date"`
	GrossSalesBySource json.RawMessage `json:"gross_sales_by_source"`
	Commissions        pgtype.Numeric  `json:"commissions"`
	Refunds            pgtype.Numeric  `json:"refunds"`
	InputCosts         pgtype.Numeric  `json:"input_costs"`
	Margin             pgtype.Numeric  `json:"margin"`
	DiscrepancyFlags   json.RawMessage `json:"discrepancy_flags"`
	SourceRowRefs      json.RawMessage `json:"source_row_refs"`
}

// Writer: internal/reconcile/ only. The model layer never calls this.
func (q *Queries) UpsertDailyReconciliation(ctx context.Context, arg UpsertDailyReconciliationParams) (DailyReconciliation, error) {
	row := q.db.QueryRow(ctx, upsertDailyReconciliation,
		arg.Date,
		arg.GrossSalesBySource,
		arg.Commissions,
		arg.Refunds,
		arg.InputCosts,
		arg.Margin,
		arg.DiscrepancyFlags,
		arg.SourceRowRefs,
	)
	var i DailyReconciliation
	err := row.Scan(
		&i.Date,
		&i.GrossSalesBySource,
		&i.Commissions,
		&i.Refunds,
		&i.InputCosts,
		&i.Margin,
		&i.DiscrepancyFlags,
		&i.SourceRowRefs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
