// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

// Exact-match answer cache keyed on normalized question text. Paraphrases deliberately do NOT hit: matching them would need a model or an embedding, which would reintroduce the cost the cache exists to avoid and put a probabilistic step in front of a deterministic lookup.
type AnswerCache struct {
	NormalizedQuestion string             `json:"normalized_question"`
	OriginalQuestion   string             `json:"original_question"`
	Response           json.RawMessage    `json:"response"`
	OriginCostUsd      pgtype.Numeric     `json:"origin_cost_usd"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

// One row per answer served from cache — a NON-interaction. Kept out of question_interaction so that table stays exactly "model calls that really ran" (Constitution Principle VI), and so cost totals are never inflated by spend that did not happen.
type AnswerCacheHit struct {
	ID                      pgtype.UUID        `json:"id"`
	NormalizedQuestion      string             `json:"normalized_question"`
	QuestionText            string             `json:"question_text"`
	EstimatedCostAvoidedUsd pgtype.Numeric     `json:"estimated_cost_avoided_usd"`
	ServedAt                pgtype.Timestamptz `json:"served_at"`
}

// Deterministic daily margin computation. margin MUST be reproducible by re-running reconciliation against source_row_refs; never written by the model layer (Constitution Principle I).
type DailyReconciliation struct {
	Date               pgtype.Date        `json:"date"`
	GrossSalesBySource json.RawMessage    `json:"gross_sales_by_source"`
	Commissions        pgtype.Numeric     `json:"commissions"`
	Refunds            pgtype.Numeric     `json:"refunds"`
	InputCosts         pgtype.Numeric     `json:"input_costs"`
	Margin             pgtype.Numeric     `json:"margin"`
	DiscrepancyFlags   json.RawMessage    `json:"discrepancy_flags"`
	SourceRowRefs      json.RawMessage    `json:"source_row_refs"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	// Per-source (delivery-platform) breakdown of the day's commission, summing to the same total as the commissions column — added for specs/003-platform-comparator's compare_platform_economics tool, which needs a platform's real per-order commission, never a flat-rate estimate (FR-001).
	CommissionsBySource json.RawMessage `json:"commissions_by_source"`
}

// roi is NULL when incremental revenue cannot be attributed (FR-013) — never estimated. Enforced by roi_requires_attribution.
type PromotionRoiRecord struct {
	ID                           pgtype.UUID               `json:"id"`
	Platform                     string                    `json:"platform"`
	CampaignID                   string                    `json:"campaign_id"`
	Period                       pgtype.Range[pgtype.Date] `json:"period"`
	Spend                        pgtype.Numeric            `json:"spend"`
	AttributedIncrementalOrders  pgtype.Int4               `json:"attributed_incremental_orders"`
	AttributedIncrementalRevenue pgtype.Numeric            `json:"attributed_incremental_revenue"`
	Roi                          pgtype.Numeric            `json:"roi"`
	FlaggedNegative              bool                      `json:"flagged_negative"`
	SourceRowRefs                json.RawMessage           `json:"source_row_refs"`
	CreatedAt                    pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz        `json:"updated_at"`
	// ingested (file pipeline, the only origin before spec 002) or owner_created (POST /api/promotions, spec 002 User Story 3).
	Origin string `json:"origin"`
	// Set only on an owner_created row whose creation was framed as replacing a promotion already flagged negative-ROI (FR-006/FR-007). Backs the Campaign-Creation badge (internal/badges) — never itself re-validated after insert, since a re-ingestion cannot retroactively invalidate an action the owner already took (spec Edge Cases).
	ReplacesCampaignID pgtype.Text `json:"replaces_campaign_id"`
}

// Per-interaction instrumentation (Constitution Principle VI): tokens, cost, latency, and whether refusal/clarification fired, from the first API call — refusal_has_no_answer_or_provenance enforces Principle II.
type QuestionInteraction struct {
	ID                  pgtype.UUID               `json:"id"`
	QuestionText        string                    `json:"question_text"`
	ResolvedPeriod      pgtype.Range[pgtype.Date] `json:"resolved_period"`
	AmbiguityGateResult string                    `json:"ambiguity_gate_result"`
	ClarificationFired  bool                      `json:"clarification_fired"`
	RefusalFired        bool                      `json:"refusal_fired"`
	AnswerText          pgtype.Text               `json:"answer_text"`
	ProvenanceRefs      json.RawMessage           `json:"provenance_refs"`
	ModelUsed           string                    `json:"model_used"`
	InputTokens         int32                     `json:"input_tokens"`
	OutputTokens        int32                     `json:"output_tokens"`
	EstimatedCostUsd    pgtype.Numeric            `json:"estimated_cost_usd"`
	LatencyMs           int32                     `json:"latency_ms"`
	CreatedAt           pgtype.Timestamptz        `json:"created_at"`
}

// One row per distinct UTC calendar day the app was opened (FR-003). No tenant/account column yet — single-owner prototype (spec 002 Assumptions); the shape to add tenant_id to if/when multi-tenant is ever built. Never pre-seeded: a fresh instance has zero rows, which is the correct, non-fabricated starting state (SC-002).
type UsageEvent struct {
	ID         pgtype.UUID        `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	OccurredOn pgtype.Date        `json:"occurred_on"`
}
