// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

// Exact-match answer cache keyed on normalized question text. Paraphrases do NOT hit THIS lookup — matching them here would need a model or an embedding, reintroducing the cost this exact-match table exists to avoid. specs/004-semantic-cache later added a second-tier check in front of this table (see internal/paraphrase) that DOES let a paraphrase reach a cached answer: one bounded Claude Haiku 4.5 call on an exact-match miss, verified against this table's real, current contents before ever being served. That is a disclosed, bounded, re-verified cost, not the unbounded one this comment originally ruled out — see internal/paraphrase's package doc for the full reasoning. This table's own behavior (key, normalization, zero-cost hit) is unchanged by that addition.
type AnswerCache struct {
	NormalizedQuestion string             `json:"normalized_question"`
	OriginalQuestion   string             `json:"original_question"`
	Response           json.RawMessage    `json:"response"`
	OriginCostUsd      pgtype.Numeric     `json:"origin_cost_usd"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	// Version of the httpapi.AskResponse JSON shape stored in response, per answercache.CurrentSchemaVersion. NULL (pre-migration rows) or any value other than the current constant is treated as a cache miss on read, never served — the same discipline frontend/src/lib/chatStorage.ts applies to browser-persisted chat threads via THREADS_VERSION.
	SchemaVersion pgtype.Int4 `json:"schema_version"`
}

// One row per answer served from cache — a NON-interaction. Kept out of question_interaction so that table stays exactly "model calls that really ran" (Constitution Principle VI), and so cost totals are never inflated by spend that did not happen.
type AnswerCacheHit struct {
	ID                      pgtype.UUID        `json:"id"`
	NormalizedQuestion      string             `json:"normalized_question"`
	QuestionText            string             `json:"question_text"`
	EstimatedCostAvoidedUsd pgtype.Numeric     `json:"estimated_cost_avoided_usd"`
	ServedAt                pgtype.Timestamptz `json:"served_at"`
}

// One row per on-demand business-insight advice call (specs/009-business-insight-advisor) — a real, owner-initiated Claude Sonnet 5 call whose kind was first derived deterministically in Go and re-verified against the posted tool results before any tokens were spent. Kept out of question_interaction (this is not the gate or explain running), answer_cache_hit (this is not free), and paraphrase_match (this avoids nothing — it IS the spend) so all four interaction states stay distinguishable and no cost is ever netted or hidden.
type BusinessInsightInteraction struct {
	ID                 pgtype.UUID        `json:"id"`
	Kind               string             `json:"kind"`
	GroundingToolCalls json.RawMessage    `json:"grounding_tool_calls"`
	AdviceText         string             `json:"advice_text"`
	ModelUsed          string             `json:"model_used"`
	InputTokens        int32              `json:"input_tokens"`
	OutputTokens       int32              `json:"output_tokens"`
	EstimatedCostUsd   pgtype.Numeric     `json:"estimated_cost_usd"`
	LatencyMs          int32              `json:"latency_ms"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

// One row per frontend crash caught by the ErrorBoundary (frontend/src/components/ErrorBoundary.tsx). Read-only feed for retrospectives, not a support ticket queue — no auth, no PII collected on purpose (single-owner prototype, per the same scope constraint as everywhere else in this build).
type ClientErrorReport struct {
	ID         pgtype.UUID        `json:"id"`
	Message    string             `json:"message"`
	Component  pgtype.Text        `json:"component"`
	Stack      pgtype.Text        `json:"stack"`
	Url        pgtype.Text        `json:"url"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

// Deterministic daily margin computation. margin MUST be reproducible by re-running reconciliation against source_row_refs; never written by the model layer (Constitution Principle I).
type DailyReconciliation struct {
	Date               pgtype.Date        `json:"date"`
	GrossSalesBySource json.RawMessage    `json:"gross_sales_by_source"`
	Commissions        pgtype.Numeric     `json:"commissions"`
	Refunds            pgtype.Numeric     `json:"refunds"`
	InputCosts         pgtype.Numeric     `json:"input_costs"`
	Margin             pgtype.Numeric     `json:"margin"`
	DiscrepancyFlags   json.RawMessage    `json:"discrepancy_flags"`
	SourceRowRefs      json.RawMessage    `json:"source_row_refs"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	// Per-source (delivery-platform) breakdown of the day's commission, summing to the same total as the commissions column — added for specs/003-platform-comparator's compare_platform_economics tool, which needs a platform's real per-order commission, never a flat-rate estimate (FR-001).
	CommissionsBySource json.RawMessage `json:"commissions_by_source"`
	// Per-source (delivery-platform) breakdown of the day's refunds, summing to the same total as the refunds column — added to close A15 (docs/product-strategy.md), a real measured eval gap: refunds could not previously be attributed to a specific platform even though internal/ingest.DeliveryRecord always carries the Platform of the refunded row.
	RefundsBySource json.RawMessage `json:"refunds_by_source"`
}

// One row per answer served via paraphrase recognition (specs/004-semantic-cache) — a real, bounded Claude Haiku 4.5 classification call (classification_cost_usd, never zero) that avoided a full gate+explain cycle (cost_avoided_usd). Kept out of both question_interaction (this is not the ambiguity gate or explain running) and answer_cache_hit (this is not free) so all three states — fresh call, exact-text hit, paraphrase hit — stay distinguishable and no cost is ever netted or hidden.
type ParaphraseMatch struct {
	ID                         pgtype.UUID        `json:"id"`
	NewQuestion                string             `json:"new_question"`
	MatchedNormalizedQuestion  string             `json:"matched_normalized_question"`
	ClassificationInputTokens  int32              `json:"classification_input_tokens"`
	ClassificationOutputTokens int32              `json:"classification_output_tokens"`
	ClassificationCostUsd      pgtype.Numeric     `json:"classification_cost_usd"`
	ClassificationLatencyMs    int32              `json:"classification_latency_ms"`
	CostAvoidedUsd             pgtype.Numeric     `json:"cost_avoided_usd"`
	MatchedAt                  pgtype.Timestamptz `json:"matched_at"`
}

// roi is NULL when incremental revenue cannot be attributed (FR-013) — never estimated. Enforced by roi_requires_attribution.
type PromotionRoiRecord struct {
	ID                           pgtype.UUID               `json:"id"`
	Platform                     string                    `json:"platform"`
	CampaignID                   string                    `json:"campaign_id"`
	Period                       pgtype.Range[pgtype.Date] `json:"period"`
	Spend                        pgtype.Numeric            `json:"spend"`
	AttributedIncrementalOrders  pgtype.Int4               `json:"attributed_incremental_orders"`
	AttributedIncrementalRevenue pgtype.Numeric            `json:"attributed_incremental_revenue"`
	Roi                          pgtype.Numeric            `json:"roi"`
	FlaggedNegative              bool                      `json:"flagged_negative"`
	SourceRowRefs                json.RawMessage           `json:"source_row_refs"`
	CreatedAt                    pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz        `json:"updated_at"`
	// ingested (file pipeline, the only origin before spec 002) or owner_created (POST /api/promotions, spec 002 User Story 3).
	Origin string `json:"origin"`
	// Set only on an owner_created row whose creation was framed as replacing a promotion already flagged negative-ROI (FR-006/FR-007). Backs the Campaign-Creation badge (internal/badges) — never itself re-validated after insert, since a re-ingestion cannot retroactively invalidate an action the owner already took (spec Edge Cases).
	ReplacesCampaignID pgtype.Text `json:"replaces_campaign_id"`
	// How this campaign's spend was funded: money (default, every row before this migration) or points (redeemed from the owner's earned Steward points balance, internal/badges). Never decided by the model — set by the owner's explicit choice at POST /api/promotions, verified server-side against the real earned-minus-spent balance before insert.
	PaymentMethod string `json:"payment_method"`
	// Points redeemed to cover this campaign's spend, at the fixed, disclosed conversion rate internal/badges.CentsPerPoint defines. NULL whenever payment_method is money. Summed across every points-paid row (regardless of period) to compute how much of the owner's earned balance is already committed — see SumPointsSpentOnPromotions.
	PointsSpent pgtype.Int4 `json:"points_spent"`
}

// Per-interaction instrumentation (Constitution Principle VI): tokens, cost, latency, and whether refusal/clarification fired, from the first API call — refusal_has_no_answer_or_provenance enforces Principle II.
type QuestionInteraction struct {
	ID                  pgtype.UUID               `json:"id"`
	QuestionText        string                    `json:"question_text"`
	ResolvedPeriod      pgtype.Range[pgtype.Date] `json:"resolved_period"`
	AmbiguityGateResult string                    `json:"ambiguity_gate_result"`
	ClarificationFired  bool                      `json:"clarification_fired"`
	RefusalFired        bool                      `json:"refusal_fired"`
	AnswerText          pgtype.Text               `json:"answer_text"`
	ProvenanceRefs      json.RawMessage           `json:"provenance_refs"`
	ModelUsed           string                    `json:"model_used"`
	InputTokens         int32                     `json:"input_tokens"`
	OutputTokens        int32                     `json:"output_tokens"`
	EstimatedCostUsd    pgtype.Numeric            `json:"estimated_cost_usd"`
	LatencyMs           int32                     `json:"latency_ms"`
	CreatedAt           pgtype.Timestamptz        `json:"created_at"`
}

// One row per distinct UTC calendar day the app was opened (FR-003). No tenant/account column yet — single-owner prototype (spec 002 Assumptions); the shape to add tenant_id to if/when multi-tenant is ever built. Never pre-seeded: a fresh instance has zero rows, which is the correct, non-fabricated starting state (SC-002).
type UsageEvent struct {
	ID         pgtype.UUID        `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	OccurredOn pgtype.Date        `json:"occurred_on"`
}
