// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: paraphrase_match.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countParaphraseMatches = `-- name: CountParaphraseMatches :one
SELECT COUNT(*)::bigint AS total FROM paraphrase_match
`

func (q *Queries) CountParaphraseMatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countParaphraseMatches)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createParaphraseMatch = `-- name: CreateParaphraseMatch :one
INSERT INTO paraphrase_match (
    new_question,
    matched_normalized_question,
    classification_input_tokens,
    classification_output_tokens,
    classification_cost_usd,
    classification_latency_ms,
    cost_avoided_usd
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, new_question, matched_normalized_question, classification_input_tokens, classification_output_tokens, classification_cost_usd, classification_latency_ms, cost_avoided_usd, matched_at
`

type CreateParaphraseMatchParams struct {
	NewQuestion                string         `json:"new_question"`
	MatchedNormalizedQuestion  string         `json:"matched_normalized_question"`
	ClassificationInputTokens  int32          `json:"classification_input_tokens"`
	ClassificationOutputTokens int32          `json:"classification_output_tokens"`
	ClassificationCostUsd      pgtype.Numeric `json:"classification_cost_usd"`
	ClassificationLatencyMs    int32          `json:"classification_latency_ms"`
	CostAvoidedUsd             pgtype.Numeric `json:"cost_avoided_usd"`
}

// One row per answer served via paraphrase recognition (specs/004-semantic-cache)
// — a real classification call that avoided a full gate+explain cycle. Both
// costs are recorded, never netted (spec FR-005).
func (q *Queries) CreateParaphraseMatch(ctx context.Context, arg CreateParaphraseMatchParams) (ParaphraseMatch, error) {
	row := q.db.QueryRow(ctx, createParaphraseMatch,
		arg.NewQuestion,
		arg.MatchedNormalizedQuestion,
		arg.ClassificationInputTokens,
		arg.ClassificationOutputTokens,
		arg.ClassificationCostUsd,
		arg.ClassificationLatencyMs,
		arg.CostAvoidedUsd,
	)
	var i ParaphraseMatch
	err := row.Scan(
		&i.ID,
		&i.NewQuestion,
		&i.MatchedNormalizedQuestion,
		&i.ClassificationInputTokens,
		&i.ClassificationOutputTokens,
		&i.ClassificationCostUsd,
		&i.ClassificationLatencyMs,
		&i.CostAvoidedUsd,
		&i.MatchedAt,
	)
	return i, err
}

const sumParaphraseMatchClassificationCost = `-- name: SumParaphraseMatchClassificationCost :one
SELECT COALESCE(SUM(classification_cost_usd), 0)::numeric AS total FROM paraphrase_match
`

// The real, small cost this project's paraphrase-matching mechanism has
// itself spent so far (spec SC-003's "small fraction of what it avoids").
func (q *Queries) SumParaphraseMatchClassificationCost(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumParaphraseMatchClassificationCost)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const sumParaphraseMatchCostAvoided = `-- name: SumParaphraseMatchCostAvoided :one
SELECT COALESCE(SUM(cost_avoided_usd), 0)::numeric AS total FROM paraphrase_match
`

// Total full-cycle spend paraphrase recognition has avoided so far.
func (q *Queries) SumParaphraseMatchCostAvoided(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumParaphraseMatchCostAvoided)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}
