// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotion_roi_record.sql

package storage

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPromotionRoiByCampaign = `-- name: GetPromotionRoiByCampaign :many
SELECT id, platform, campaign_id, period, spend, attributed_incremental_orders, attributed_incremental_revenue, roi, flagged_negative, source_row_refs, created_at, updated_at FROM promotion_roi_record
WHERE campaign_id = $1
ORDER BY period
`

// Backs the get_promotion_roi MCP tool contract (campaign_id input form).
func (q *Queries) GetPromotionRoiByCampaign(ctx context.Context, campaignID string) ([]PromotionRoiRecord, error) {
	rows, err := q.db.Query(ctx, getPromotionRoiByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromotionRoiRecord
	for rows.Next() {
		var i PromotionRoiRecord
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.CampaignID,
			&i.Period,
			&i.Spend,
			&i.AttributedIncrementalOrders,
			&i.AttributedIncrementalRevenue,
			&i.Roi,
			&i.FlaggedNegative,
			&i.SourceRowRefs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromotionRoiByPlatformAndPeriod = `-- name: GetPromotionRoiByPlatformAndPeriod :many
SELECT id, platform, campaign_id, period, spend, attributed_incremental_orders, attributed_incremental_revenue, roi, flagged_negative, source_row_refs, created_at, updated_at FROM promotion_roi_record
WHERE platform = $1 AND period && $2::daterange
ORDER BY period
`

type GetPromotionRoiByPlatformAndPeriodParams struct {
	Platform string                    `json:"platform"`
	Column2  pgtype.Range[pgtype.Date] `json:"column_2"`
}

// Backs the get_promotion_roi MCP tool contract (platform+period input form).
func (q *Queries) GetPromotionRoiByPlatformAndPeriod(ctx context.Context, arg GetPromotionRoiByPlatformAndPeriodParams) ([]PromotionRoiRecord, error) {
	rows, err := q.db.Query(ctx, getPromotionRoiByPlatformAndPeriod, arg.Platform, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromotionRoiRecord
	for rows.Next() {
		var i PromotionRoiRecord
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.CampaignID,
			&i.Period,
			&i.Spend,
			&i.AttributedIncrementalOrders,
			&i.AttributedIncrementalRevenue,
			&i.Roi,
			&i.FlaggedNegative,
			&i.SourceRowRefs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctCampaignIDs = `-- name: ListDistinctCampaignIDs :many
SELECT DISTINCT campaign_id FROM promotion_roi_record ORDER BY campaign_id
`

// Backs the campaign-lookup fuzzy-match fix (docs/plan.md mistakes log:
// "campaign name/entity lookup defect"): the real, bounded set of
// campaign_id values that actually exist, so a human-readable name or
// shortened form (e.g. "LUNCHFIX", or the full display name "Banner Ad -
// Lunch Fix Menu (JET-CAMP-LUNCHFIX)") can be matched against the known
// set in Go code (internal/mcptools) rather than requiring an exact
// string match or letting the model guess an id that doesn't exist
// (Constitution Principle III: a typed, bounded match, never open-ended
// fuzzy computation).
func (q *Queries) ListDistinctCampaignIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctCampaignIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var campaign_id string
		if err := rows.Scan(&campaign_id); err != nil {
			return nil, err
		}
		items = append(items, campaign_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNegativeRoiPromotions = `-- name: ListNegativeRoiPromotions :many
SELECT id, platform, campaign_id, period, spend, attributed_incremental_orders, attributed_incremental_revenue, roi, flagged_negative, source_row_refs, created_at, updated_at FROM promotion_roi_record
WHERE flagged_negative = true AND period && $1::daterange
ORDER BY period
`

// Backs the list_negative_roi_promotions MCP tool contract (spec User Story 4 / SC-006).
func (q *Queries) ListNegativeRoiPromotions(ctx context.Context, dollar_1 pgtype.Range[pgtype.Date]) ([]PromotionRoiRecord, error) {
	rows, err := q.db.Query(ctx, listNegativeRoiPromotions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromotionRoiRecord
	for rows.Next() {
		var i PromotionRoiRecord
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.CampaignID,
			&i.Period,
			&i.Spend,
			&i.AttributedIncrementalOrders,
			&i.AttributedIncrementalRevenue,
			&i.Roi,
			&i.FlaggedNegative,
			&i.SourceRowRefs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPromotionRoiRecord = `-- name: UpsertPromotionRoiRecord :one
INSERT INTO promotion_roi_record (
    platform,
    campaign_id,
    period,
    spend,
    attributed_incremental_orders,
    attributed_incremental_revenue,
    roi,
    flagged_negative,
    source_row_refs
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (platform, campaign_id, period) DO UPDATE SET
    spend                          = EXCLUDED.spend,
    attributed_incremental_orders  = EXCLUDED.attributed_incremental_orders,
    attributed_incremental_revenue = EXCLUDED.attributed_incremental_revenue,
    roi                            = EXCLUDED.roi,
    flagged_negative               = EXCLUDED.flagged_negative,
    source_row_refs                = EXCLUDED.source_row_refs,
    updated_at                     = now()
RETURNING id, platform, campaign_id, period, spend, attributed_incremental_orders, attributed_incremental_revenue, roi, flagged_negative, source_row_refs, created_at, updated_at
`

type UpsertPromotionRoiRecordParams struct {
	Platform                     string                    `json:"platform"`
	CampaignID                   string                    `json:"campaign_id"`
	Period                       pgtype.Range[pgtype.Date] `json:"period"`
	Spend                        pgtype.Numeric            `json:"spend"`
	AttributedIncrementalOrders  pgtype.Int4               `json:"attributed_incremental_orders"`
	AttributedIncrementalRevenue pgtype.Numeric            `json:"attributed_incremental_revenue"`
	Roi                          pgtype.Numeric            `json:"roi"`
	FlaggedNegative              bool                      `json:"flagged_negative"`
	SourceRowRefs                json.RawMessage           `json:"source_row_refs"`
}

// Writer: internal/reconcile/ only. roi/attributed_* are NULL together when
// attribution is unavailable (FR-013) — this query never fills them in.
func (q *Queries) UpsertPromotionRoiRecord(ctx context.Context, arg UpsertPromotionRoiRecordParams) (PromotionRoiRecord, error) {
	row := q.db.QueryRow(ctx, upsertPromotionRoiRecord,
		arg.Platform,
		arg.CampaignID,
		arg.Period,
		arg.Spend,
		arg.AttributedIncrementalOrders,
		arg.AttributedIncrementalRevenue,
		arg.Roi,
		arg.FlaggedNegative,
		arg.SourceRowRefs,
	)
	var i PromotionRoiRecord
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.CampaignID,
		&i.Period,
		&i.Spend,
		&i.AttributedIncrementalOrders,
		&i.AttributedIncrementalRevenue,
		&i.Roi,
		&i.FlaggedNegative,
		&i.SourceRowRefs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
