// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Writer: internal/instrumentation/ only, alongside whichever of
	// internal/ambiguity/ or internal/explain/ ran (Constitution Principle VI).
	CreateQuestionInteraction(ctx context.Context, arg CreateQuestionInteractionParams) (QuestionInteraction, error)
	// Backs the get_daily_summary MCP tool contract.
	GetDailyReconciliationByDate(ctx context.Context, date pgtype.Date) (DailyReconciliation, error)
	// Backs the get_promotion_roi MCP tool contract (campaign_id input form).
	GetPromotionRoiByCampaign(ctx context.Context, campaignID string) ([]PromotionRoiRecord, error)
	// Backs the get_promotion_roi MCP tool contract (platform+period input form).
	GetPromotionRoiByPlatformAndPeriod(ctx context.Context, arg GetPromotionRoiByPlatformAndPeriodParams) ([]PromotionRoiRecord, error)
	// Backs get_margin_delta / list_discrepancies, which operate over a range.
	ListDailyReconciliationsInPeriod(ctx context.Context, arg ListDailyReconciliationsInPeriodParams) ([]DailyReconciliation, error)
	// Backs the list_negative_roi_promotions MCP tool contract (spec User Story 4 / SC-006).
	ListNegativeRoiPromotions(ctx context.Context, dollar_1 pgtype.Range[pgtype.Date]) ([]PromotionRoiRecord, error)
	// Backs an instrumentation/history view in the frontend cost panel.
	ListRecentQuestionInteractions(ctx context.Context, limit int32) ([]QuestionInteraction, error)
	// Backs the running cost total the UI must show for 100% of interactions (FR-009).
	SumEstimatedCostUSD(ctx context.Context) (pgtype.Numeric, error)
	// Writer: internal/reconcile/ only. The model layer never calls this.
	UpsertDailyReconciliation(ctx context.Context, arg UpsertDailyReconciliationParams) (DailyReconciliation, error)
	// Writer: internal/reconcile/ only. roi/attributed_* are NULL together when
	// attribution is unavailable (FR-013) — this query never fills them in.
	UpsertPromotionRoiRecord(ctx context.Context, arg UpsertPromotionRoiRecordParams) (PromotionRoiRecord, error)
}

var _ Querier = (*Queries)(nil)
