// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAnswerCacheHits(ctx context.Context) (int64, error)
	CountBusinessInsightInteractions(ctx context.Context) (int64, error)
	CountParaphraseMatches(ctx context.Context) (int64, error)
	// One row per answer served from cache — a non-interaction, recorded in its
	// own ledger rather than as a fabricated question_interaction.
	CreateAnswerCacheHit(ctx context.Context, arg CreateAnswerCacheHitParams) (AnswerCacheHit, error)
	// One row per on-demand business-insight advice call
	// (specs/009-business-insight-advisor) — the owner tapped a
	// deterministically-derived teaser and a real Claude Sonnet 5 call ran.
	// Writer: internal/httpapi's business-insight handler only, alongside
	// internal/advisor's model call (Constitution Principle VI).
	CreateBusinessInsightInteraction(ctx context.Context, arg CreateBusinessInsightInteractionParams) (BusinessInsightInteraction, error)
	// Backs POST /api/promotions (User Story 3): the owner logging a new
	// promotion record directly in the app, per FR-005/FR-006. Deliberately a
	// plain INSERT, not the same ON CONFLICT upsert UpsertPromotionRoiRecord
	// uses for the ingestion pipeline — a second submission with the same
	// platform/campaign_id/period is a genuine new attempt from a human, not a
	// re-run of the same deterministic computation, so a unique-violation here
	// should surface as a real "that campaign already exists" error
	// (internal/httpapi), not silently overwrite what's there.
	//
	// attributed_incremental_orders/revenue and roi are never supplied here: an
	// owner-created record has not been through attribution at all (no
	// delivery-platform data has been tagged to it yet), which is a DIFFERENT
	// fact from FR-013's "unattributable after trying" — both render the same
	// way (roi: null) because both really are "no ROI is known", never a
	// computed-looking zero.
	CreateOwnerPromotion(ctx context.Context, arg CreateOwnerPromotionParams) (PromotionRoiRecord, error)
	// One row per answer served via paraphrase recognition (specs/004-semantic-cache)
	// — a real classification call that avoided a full gate+explain cycle. Both
	// costs are recorded, never netted (spec FR-005).
	CreateParaphraseMatch(ctx context.Context, arg CreateParaphraseMatchParams) (ParaphraseMatch, error)
	// Writer: internal/instrumentation/ only, alongside whichever of
	// internal/ambiguity/ or internal/explain/ ran (Constitution Principle VI).
	CreateQuestionInteraction(ctx context.Context, arg CreateQuestionInteractionParams) (QuestionInteraction, error)
	// Invalidation. Called at the START of every ingestion run: new source data
	// can change any cached answer, and there is no cheap way to know which, so
	// the whole cache is dropped. Correctness after new data beats cache
	// retention, always.
	DeleteAllAnswerCacheEntries(ctx context.Context) error
	// Exact lookup on the normalized question key. Writer/reader:
	// internal/answercache only.
	GetAnswerCacheEntry(ctx context.Context, normalizedQuestion string) (AnswerCache, error)
	// Backs the get_daily_summary MCP tool contract.
	GetDailyReconciliationByDate(ctx context.Context, date pgtype.Date) (DailyReconciliation, error)
	// Backs the date-grounding fix (docs/plan.md mistakes log: "date-year
	// grounding defect"): the actual inclusive min/max date this product has
	// ANY reconciled data for, resolved once at process start
	// (cmd/server/main.go) and handed into internal/ambiguity's gate and
	// internal/explain's system prompt as plain strings, so relative date
	// language ("today", "this week", a year-less date) resolves against the
	// real data's own range instead of the host machine's wall-clock date or
	// a hardcoded literal that could drift from the fixtures actually loaded.
	GetDataDateRange(ctx context.Context) (GetDataDateRangeRow, error)
	// Backs the get_promotion_roi MCP tool contract (campaign_id input form).
	GetPromotionRoiByCampaign(ctx context.Context, campaignID string) ([]PromotionRoiRecord, error)
	// Backs the get_promotion_roi MCP tool contract (platform+period input form).
	GetPromotionRoiByPlatformAndPeriod(ctx context.Context, arg GetPromotionRoiByPlatformAndPeriodParams) ([]PromotionRoiRecord, error)
	// Backs GET /api/profile. Returns pgx.ErrNoRows when the owner has not
	// saved a profile yet (id=1 never inserted) — the handler renders that as
	// an empty, not-yet-configured profile rather than an error.
	GetRestaurantProfile(ctx context.Context) (RestaurantProfile, error)
	// Backs GET /api/promotions (internal/httpapi/data.go): the whole promotion
	// set for the Promotions page, which is a deliberate full listing rather
	// than a period query — the page's job is "every campaign on file and
	// whether it paid for itself", and silently scoping it to a default window
	// would hide campaigns rather than answer that question.
	ListAllPromotionRoiRecords(ctx context.Context) ([]PromotionRoiRecord, error)
	// Backs get_margin_delta / list_discrepancies, which operate over a range.
	ListDailyReconciliationsInPeriod(ctx context.Context, arg ListDailyReconciliationsInPeriodParams) ([]DailyReconciliation, error)
	// Backs the campaign-lookup fuzzy-match fix (docs/plan.md mistakes log:
	// "campaign name/entity lookup defect"): the real, bounded set of
	// campaign_id values that actually exist, so a human-readable name or
	// shortened form (e.g. "LUNCHFIX", or the full display name "Banner Ad -
	// Lunch Fix Menu (JET-CAMP-LUNCHFIX)") can be matched against the known
	// set in Go code (internal/mcptools) rather than requiring an exact
	// string match or letting the model guess an id that doesn't exist
	// (Constitution Principle III: a typed, bounded match, never open-ended
	// fuzzy computation).
	ListDistinctCampaignIDs(ctx context.Context) ([]string, error)
	// Backs Engagement badge evaluation (FR-004): every distinct UTC calendar
	// day the app has genuinely been opened on, oldest first. The unique index
	// on occurred_on already guarantees one row per day, so this is a plain
	// ordered read, not a DISTINCT/GROUP BY doing real deduplication work.
	ListDistinctUsageDays(ctx context.Context) ([]pgtype.Date, error)
	// Backs the list_negative_roi_promotions MCP tool contract (spec User Story 4 / SC-006).
	ListNegativeRoiPromotions(ctx context.Context, dollar_1 pgtype.Range[pgtype.Date]) ([]PromotionRoiRecord, error)
	// The bounded candidate set specs/004-semantic-cache's paraphrase classifier
	// checks a new question against: the most-recently-cached questions first
	// (LIMIT applies the plan's cap — 20 at the call site — before the
	// classification prompt is built, per plan.md's "Candidate-set cap" section).
	// Already distinct by construction: normalized_question is answer_cache's
	// primary key, so this can never return two rows for the same question.
	ListRecentDistinctCachedQuestions(ctx context.Context, limit int32) ([]ListRecentDistinctCachedQuestionsRow, error)
	// Backs an instrumentation/history view in the frontend cost panel.
	ListRecentQuestionInteractions(ctx context.Context, limit int32) ([]QuestionInteraction, error)
	// Backs POST /api/client-errors (frontend/src/components/ErrorBoundary.tsx).
	// A pure insert of what the browser reported about itself — no
	// interpretation, no join against any other table. See
	// migrations/000006_client_error_report.up.sql for why this is its own
	// table rather than folded into an existing one.
	RecordClientErrorReport(ctx context.Context, arg RecordClientErrorReportParams) (ClientErrorReport, error)
	// Backs FR-003: one real, timestamped usage event per real app-open. The
	// ON CONFLICT no-op is the actual mechanism behind "no double-counting
	// within a calendar day, no manual dedup required of the caller" (spec 002
	// User Story 2 Acceptance Scenario 3) — occurred_on is a generated column
	// with a unique index (migrations/000003), so a second ping on the same UTC
	// day can never insert a second row. DO NOTHING has no RETURNING row on a
	// conflict, so the Go caller (internal/httpapi) does its own
	// already-recorded-today check rather than relying on this query's return
	// value alone; see storage/usage_event.go's RecordUsageEvent wrapper.
	RecordUsageEvent(ctx context.Context) (UsageEvent, error)
	// Total model spend the cache has avoided so far.
	SumAnswerCacheCostAvoided(ctx context.Context) (pgtype.Numeric, error)
	// The real total this product's advice skill has spent so far — its own
	// ledger's sum, never mixed into question_interaction's running total.
	SumBusinessInsightCost(ctx context.Context) (pgtype.Numeric, error)
	// Backs the running cost total the UI must show for 100% of interactions (FR-009).
	SumEstimatedCostUSD(ctx context.Context) (pgtype.Numeric, error)
	// The real, small cost this project's paraphrase-matching mechanism has
	// itself spent so far (spec SC-003's "small fraction of what it avoids").
	SumParaphraseMatchClassificationCost(ctx context.Context) (pgtype.Numeric, error)
	// Total full-cycle spend paraphrase recognition has avoided so far.
	SumParaphraseMatchCostAvoided(ctx context.Context) (pgtype.Numeric, error)
	// The other half of a points BALANCE (internal/badges.EvaluatePoints only
	// ever computes what's been EARNED): every point already committed to a
	// promotion's spend, regardless of that promotion's own period, since a
	// redeemed point stays spent forever, not just within one reporting window.
	// COALESCE keeps a fresh instance with zero points-paid rows at a real 0,
	// never NULL, so callers never special-case "no rows yet".
	SumPointsSpentOnPromotions(ctx context.Context) (int64, error)
	// Re-answering the same normalized question overwrites the entry rather than
	// keeping the older one: the newer response was computed against whatever
	// data is current, so it is the one worth serving next time.
	//
	// schema_version is always written explicitly as the CURRENT
	// answercache.CurrentSchemaVersion (see migration 000007) — never left to a
	// column default — so a later mismatch on read means exactly one thing:
	// this row predates (or postdates, after a rollback) the reader's own
	// AskResponse shape.
	UpsertAnswerCacheEntry(ctx context.Context, arg UpsertAnswerCacheEntryParams) (AnswerCache, error)
	// Writer: internal/reconcile/ only. The model layer never calls this.
	UpsertDailyReconciliation(ctx context.Context, arg UpsertDailyReconciliationParams) (DailyReconciliation, error)
	// Writer: internal/reconcile/ only. roi/attributed_* are NULL together when
	// attribution is unavailable (FR-013) — this query never fills them in.
	UpsertPromotionRoiRecord(ctx context.Context, arg UpsertPromotionRoiRecordParams) (PromotionRoiRecord, error)
	// Writer: internal/httpapi's profile handler only (PUT /api/profile).
	// restaurant_profile is pinned to exactly one row (id=1, see migration
	// 000011) — this is a full replace of that one row, not a partial patch,
	// so the caller must pass every field's intended final value, including an
	// unchanged photo it read back from GET /api/profile.
	UpsertRestaurantProfile(ctx context.Context, arg UpsertRestaurantProfileParams) (RestaurantProfile, error)
}

var _ Querier = (*Queries)(nil)
