// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: question_interaction.sql

package storage

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestionInteraction = `-- name: CreateQuestionInteraction :one
INSERT INTO question_interaction (
    question_text,
    resolved_period,
    ambiguity_gate_result,
    clarification_fired,
    refusal_fired,
    answer_text,
    provenance_refs,
    model_used,
    input_tokens,
    output_tokens,
    estimated_cost_usd,
    latency_ms
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, question_text, resolved_period, ambiguity_gate_result, clarification_fired, refusal_fired, answer_text, provenance_refs, model_used, input_tokens, output_tokens, estimated_cost_usd, latency_ms, created_at
`

type CreateQuestionInteractionParams struct {
	QuestionText        string                    `json:"question_text"`
	ResolvedPeriod      pgtype.Range[pgtype.Date] `json:"resolved_period"`
	AmbiguityGateResult string                    `json:"ambiguity_gate_result"`
	ClarificationFired  bool                      `json:"clarification_fired"`
	RefusalFired        bool                      `json:"refusal_fired"`
	AnswerText          pgtype.Text               `json:"answer_text"`
	ProvenanceRefs      json.RawMessage           `json:"provenance_refs"`
	ModelUsed           string                    `json:"model_used"`
	InputTokens         int32                     `json:"input_tokens"`
	OutputTokens        int32                     `json:"output_tokens"`
	EstimatedCostUsd    pgtype.Numeric            `json:"estimated_cost_usd"`
	LatencyMs           int32                     `json:"latency_ms"`
}

// Writer: internal/instrumentation/ only, alongside whichever of
// internal/ambiguity/ or internal/explain/ ran (Constitution Principle VI).
func (q *Queries) CreateQuestionInteraction(ctx context.Context, arg CreateQuestionInteractionParams) (QuestionInteraction, error) {
	row := q.db.QueryRow(ctx, createQuestionInteraction,
		arg.QuestionText,
		arg.ResolvedPeriod,
		arg.AmbiguityGateResult,
		arg.ClarificationFired,
		arg.RefusalFired,
		arg.AnswerText,
		arg.ProvenanceRefs,
		arg.ModelUsed,
		arg.InputTokens,
		arg.OutputTokens,
		arg.EstimatedCostUsd,
		arg.LatencyMs,
	)
	var i QuestionInteraction
	err := row.Scan(
		&i.ID,
		&i.QuestionText,
		&i.ResolvedPeriod,
		&i.AmbiguityGateResult,
		&i.ClarificationFired,
		&i.RefusalFired,
		&i.AnswerText,
		&i.ProvenanceRefs,
		&i.ModelUsed,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCostUsd,
		&i.LatencyMs,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentQuestionInteractions = `-- name: ListRecentQuestionInteractions :many
SELECT id, question_text, resolved_period, ambiguity_gate_result, clarification_fired, refusal_fired, answer_text, provenance_refs, model_used, input_tokens, output_tokens, estimated_cost_usd, latency_ms, created_at FROM question_interaction
ORDER BY created_at DESC
LIMIT $1
`

// Backs an instrumentation/history view in the frontend cost panel.
func (q *Queries) ListRecentQuestionInteractions(ctx context.Context, limit int32) ([]QuestionInteraction, error) {
	rows, err := q.db.Query(ctx, listRecentQuestionInteractions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionInteraction
	for rows.Next() {
		var i QuestionInteraction
		if err := rows.Scan(
			&i.ID,
			&i.QuestionText,
			&i.ResolvedPeriod,
			&i.AmbiguityGateResult,
			&i.ClarificationFired,
			&i.RefusalFired,
			&i.AnswerText,
			&i.ProvenanceRefs,
			&i.ModelUsed,
			&i.InputTokens,
			&i.OutputTokens,
			&i.EstimatedCostUsd,
			&i.LatencyMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumEstimatedCostUSD = `-- name: SumEstimatedCostUSD :one
SELECT COALESCE(SUM(estimated_cost_usd), 0)::numeric AS total_cost_usd
FROM question_interaction
`

// Backs the running cost total the UI must show for 100% of interactions (FR-009).
func (q *Queries) SumEstimatedCostUSD(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumEstimatedCostUSD)
	var total_cost_usd pgtype.Numeric
	err := row.Scan(&total_cost_usd)
	return total_cost_usd, err
}
