// Package livedata is the single source of truth for the dataset
// directory specs/007-cost-sheet-upload writes into: backend/data/live/,
// the git-ignored directory holding the product's one continuous dataset
// (generated by cmd/gendata, whose first 14 days are the hand-authored
// opening window checked in at cmd/gendata/opening/). Real web-UI uploads
// modify this directory going forward.
//
// The guarantee this package provides: Dir is a fixed, hardcoded location,
// resolved at package-init time from THIS FILE's own compile-time location
// (runtime.Caller), never from os.Getwd() or any request input. This
// project's dev server has actually been started from different working
// directories across sessions (repo root for some -ingest invocations per
// specs/001-margin-reconciliation-qa/quickstart.md, backend/ for how
// -serve has actually been launched elsewhere) — an os.Getwd()-relative
// path would silently resolve to a different directory depending on that
// accident of invocation. Anchoring to runtime.Caller(0) makes Dir a true
// constant: the same absolute path every run, and one that no request can
// ever influence because no request-derived string ever participates in
// building it.
package livedata

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

var (
	// backendDir is backend/ — this file's own directory
	// (backend/internal/livedata) two levels up — resolved once, at
	// package-init time, from the compiled-in source path rather than the
	// process's current working directory.
	backendDir = func() string {
		_, thisFile, _, ok := runtime.Caller(0)
		if !ok {
			// Unreachable in practice (runtime.Caller(0) always succeeds for
			// the calling frame itself), but fail loudly rather than silently
			// falling back to a guessed path if it ever were to happen —
			// Constitution Principle II applies to this package's own
			// bootstrapping, not just to parsed data.
			panic("livedata: runtime.Caller(0) failed to resolve this package's own source location")
		}
		return filepath.Dir(filepath.Dir(filepath.Dir(thisFile)))
	}()

	// Dir is the dataset directory real uploads modify: backend/data/live/.
	// Git-ignored (see .gitignore) — never the destination of a git commit.
	Dir = filepath.Join(backendDir, "data", "live")
)

// EnsureReady verifies Dir exists and holds at least one CSV — the state
// `go run ./cmd/gendata -out data/live` (from backend/) leaves it in.
// There is deliberately no automatic bootstrap here: an upload committed
// into an otherwise-empty directory would re-ingest a "dataset" of one
// lone cost sheet, silently replacing the whole reconciled timeline with
// 14 days of supplier invoices and nothing else. Refusing with an explicit
// instruction beats that outcome every time (Constitution Principle II).
func EnsureReady() error {
	entries, err := os.ReadDir(Dir)
	if err != nil {
		return fmt.Errorf("livedata: dataset directory %s is not usable (run `go run ./cmd/gendata -out data/live` from backend/ to generate it): %w", Dir, err)
	}
	for _, e := range entries {
		if !e.IsDir() && strings.EqualFold(filepath.Ext(e.Name()), ".csv") {
			return nil
		}
	}
	return fmt.Errorf("livedata: dataset directory %s holds no CSVs (run `go run ./cmd/gendata -out data/live` from backend/ to generate the dataset)", Dir)
}
