/**
 * THE authoritative frontend catalog of what this product can actually do.
 *
 * Why this file exists at all: "a hand-maintained list of capabilities" has
 * gone stale in this codebase twice — the Help page hardcoded "seven tools"
 * after an eighth shipped, and `Chat/exampleQuestions.ts` still has no entry
 * for that eighth tool. Both failures had the same root cause: several
 * independent lists, each of which a person had to remember to update. This
 * module is the one list. Every "what can I do here" surface reads from it
 * rather than restating it.
 *
 * Two things keep it honest, and neither is a person remembering:
 *
 *  1. **A contract test against the real Go code.** `capabilities.test.ts`
 *     parses `backend/internal/mcptools/*.go` for every `mcp.NewTool("…")`
 *     actually registered, and `backend/internal/advisor/advisor.go` for
 *     every insight `Kind…` constant, and asserts this file's two lists match
 *     them EXACTLY — in both directions. Ship a ninth MCP tool and the
 *     frontend test suite goes red naming the tool nobody surfaced. That is
 *     the mechanism the previous two lists lacked.
 *
 *  2. **Types the compiler enforces.** `McpToolName` and `BusinessInsightKind`
 *     are derived from the const tuples below, so a capability entry can only
 *     name a tool/kind this file already knows about.
 *
 * Deliberately NOT a codegen pipeline. The Go tool contracts are stable, the
 * plain-language labels are human copy that no generator could write, and a
 * generated-file build step is real ongoing cost for a fixed set of eight
 * tools. A test that fails loudly on drift buys the same guarantee for a
 * fraction of the machinery.
 *
 * Equally deliberately NOT generated by asking the model to describe its own
 * capabilities — the reason `exampleQuestions.ts`'s doc comment already
 * gives: a model listing what it can do is a fresh hallucination surface, and
 * offering a question the product cannot answer is the same class of lie as
 * inventing a number.
 *
 * Framework-free on purpose (no React, no imports): the composer, the Help
 * page, and any future consumer all read it, and its contract test parses Go
 * source in a plain Node context.
 */

// ---------------------------------------------------------------------------
// The two closed sets this product is built on
// ---------------------------------------------------------------------------

/**
 * Every typed MCP tool the model may call — the complete, fixed set from
 * `specs/001-margin-reconciliation-qa/contracts/mcp-tools.md`, registered in
 * `backend/internal/mcptools/`. There is no open SQL and no free-form
 * computation tool behind these (Constitution Principle III), so this list is
 * a genuinely exhaustive statement of what the system can COMPUTE.
 */
export const MCP_TOOL_NAMES = [
  'get_daily_summary',
  'get_margin_delta',
  'list_discrepancies',
  'get_promotion_roi',
  'list_negative_roi_promotions',
  'compare_platform_economics',
  'get_period_totals',
  'get_expense_pattern_by_day_of_month',
] as const

export type McpToolName = (typeof MCP_TOOL_NAMES)[number]

/**
 * Every business-insight kind the advisor recognizes — the five closed-set
 * kinds in `backend/internal/advisor/advisor.go`, each triggered by a real
 * computed pattern that `httpapi.deriveBusinessInsightTeaser` detects
 * deterministically in Go, with zero model calls.
 */
export const BUSINESS_INSIGHT_KINDS = [
  'discrepancy_pattern',
  'negative_promo_roi',
  'high_commission',
  'day_of_month_expense_spike',
  'margin_decline',
] as const

export type BusinessInsightKind = (typeof BUSINESS_INSIGHT_KINDS)[number]

// ---------------------------------------------------------------------------
// Computed capabilities — one per MCP tool
// ---------------------------------------------------------------------------

export type ComputedCapabilityId =
  | 'daily_summary'
  | 'margin_delta'
  | 'discrepancies'
  | 'promotion_roi'
  | 'negative_roi_promotions'
  | 'platform_economics'
  | 'period_totals'
  | 'expense_pattern_by_day'

/**
 * One thing the product can COMPUTE: a deterministic, provenance-backed fact
 * produced by exactly one typed MCP tool. Answering one of these is never a
 * judgment call, so the guided composer can offer it unconditionally — the
 * question it builds is answerable by construction.
 *
 * `tool` is never rendered in the composer's UI (the point of a
 * plain-language label is that `get_expense_pattern_by_day_of_month` never
 * appears on screen), but the Help page does show it, and the contract test
 * checks it against the Go registry.
 */
export interface ComputedCapability {
  nature: 'computed'
  id: ComputedCapabilityId
  tool: McpToolName
  /** Sentence-case, verb-first button label. No terminal punctuation. */
  label: string
  /** One-line helper sentence shown under the label. */
  description: string
}

/** Order here is the order the composer's Step 1 renders them in. */
export const COMPUTED_CAPABILITIES: ComputedCapability[] = [
  {
    nature: 'computed',
    id: 'daily_summary',
    tool: 'get_daily_summary',
    label: 'Check a single day',
    description: 'Margin, sales, and costs for one date.',
  },
  {
    nature: 'computed',
    id: 'margin_delta',
    tool: 'get_margin_delta',
    label: 'Compare two periods',
    description: 'See how margin changed between two date ranges.',
  },
  {
    nature: 'computed',
    id: 'discrepancies',
    tool: 'list_discrepancies',
    label: 'Check for discrepancies',
    description: 'Duplicate orders, refunds, and other flagged issues.',
  },
  {
    nature: 'computed',
    id: 'promotion_roi',
    tool: 'get_promotion_roi',
    label: "Check a promotion's return",
    description: "How one campaign, or a platform's campaigns, performed.",
  },
  {
    nature: 'computed',
    id: 'negative_roi_promotions',
    tool: 'list_negative_roi_promotions',
    label: 'Find money-losing promotions',
    description: 'Campaigns that cost more than they brought in.',
  },
  {
    nature: 'computed',
    id: 'platform_economics',
    tool: 'compare_platform_economics',
    label: 'Compare delivery platforms',
    description: 'Commission and promo cost, side by side.',
  },
  {
    nature: 'computed',
    id: 'period_totals',
    tool: 'get_period_totals',
    label: 'Get period totals',
    description: 'Total margin, plus your best and worst day.',
  },
  {
    nature: 'computed',
    id: 'expense_pattern_by_day',
    tool: 'get_expense_pattern_by_day_of_month',
    label: 'Find your priciest day of the month',
    description: 'Which day of the month tends to cost the most, on average.',
  },
]

// ---------------------------------------------------------------------------
// The advisory capability — one per insight kind
// ---------------------------------------------------------------------------

/**
 * One thing the product can ADVISE on: general business practice connected to
 * a real computed pattern, generated by one billed Claude Sonnet 5 call
 * (`POST /api/business-insight`, `backend/internal/advisor/`).
 *
 * This is a fundamentally different epistemic category from a
 * {@link ComputedCapability} and must be presented as one everywhere it
 * appears — probabilistic guidance, not a provenance-backed fact.
 *
 * `groundedBy` is the load-bearing field, and it encodes a real backend
 * constraint rather than a UI convenience. `HandleBusinessInsight` REFUSES any
 * advice request whose posted `tool_calls` don't re-derive to the claimed kind
 * (spec SC-005) — so advice cannot be requested out of thin air, and there is
 * no "just POST the kind" path to model. Every insight kind is reachable only
 * by first computing the pattern it is about, which is exactly what the named
 * computed capability's question does. Advice is therefore always a two-stage
 * action: compute the fact, then optionally pay for interpretation of it.
 *
 * `unavailableNote` is the honest copy for the outcome that is not an error:
 * the question was answered correctly and the pattern simply is not present.
 */
export interface AdvisoryCapability {
  nature: 'advisory'
  insightKind: BusinessInsightKind
  /** Sentence-case, verb-first button label. No terminal punctuation. */
  label: string
  /** One-line helper sentence shown under the label. */
  description: string
  /** The computed capability whose question surfaces this pattern. */
  groundedBy: ComputedCapabilityId
  /** Shown when the grounding answer came back clean — good news, not a failure. */
  unavailableNote: string
}

export const ADVISORY_CAPABILITIES: AdvisoryCapability[] = [
  {
    nature: 'advisory',
    insightKind: 'discrepancy_pattern',
    label: 'Advice on recurring discrepancies',
    description: 'What owners typically do about duplicates, refunds, and mismatches.',
    groundedBy: 'discrepancies',
    unavailableNote:
      'Nothing was flagged in this period, so there is no discrepancy pattern to advise on — that is a good result, not a missing answer.',
  },
  {
    nature: 'advisory',
    insightKind: 'negative_promo_roi',
    label: 'Advice on a promotion that lost money',
    description: 'How owners usually restructure or retire a negative-ROI campaign.',
    groundedBy: 'negative_roi_promotions',
    unavailableNote:
      'No campaign in this period was flagged as losing money, so there is nothing to advise on here.',
  },
  {
    nature: 'advisory',
    insightKind: 'high_commission',
    label: 'Advice on a high commission rate',
    description: 'Options when a platform rate sits in the premium band.',
    groundedBy: 'platform_economics',
    unavailableNote:
      'Neither platform’s effective commission rate reached the premium band in this period, so there is nothing to advise on here.',
  },
  {
    nature: 'advisory',
    insightKind: 'day_of_month_expense_spike',
    label: 'Advice on a costly day of the month',
    description: 'Ways owners smooth a recurring same-day cost spike.',
    groundedBy: 'expense_pattern_by_day',
    unavailableNote:
      'No day of the month stood out as unusually expensive in this period, so there is nothing to advise on here.',
  },
  {
    nature: 'advisory',
    insightKind: 'margin_decline',
    label: 'Advice on a margin decline',
    description: 'Which levers to review when margin drops between periods.',
    groundedBy: 'margin_delta',
    unavailableNote:
      'Margin did not decline materially between these periods, so there is nothing to advise on here.',
  },
]

/** Every capability this product has, computed and advisory alike. */
export const PRODUCT_CAPABILITIES: (ComputedCapability | AdvisoryCapability)[] = [
  ...COMPUTED_CAPABILITIES,
  ...ADVISORY_CAPABILITIES,
]

/** The advisory capability for `kind`, or `undefined` for an unknown kind. */
export function findAdvisoryCapability(
  kind: string,
): AdvisoryCapability | undefined {
  return ADVISORY_CAPABILITIES.find((c) => c.insightKind === kind)
}
